version: '3.9'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=foda
      - DB_USERNAME=foda
      - DB_PASSWORD=foda
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    ports:
      - '8080:8080'
    depends_on:
      - app
    volumes:
      - ./frontend:/usr/src/app
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: foda
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: foda
      MYSQL_PASSWORD: foda
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
