import {
  BarChart3,
  ClipboardList,
  Crown,
  Gauge,
  Globe2,
  MapPin,
  Megaphone,
  Settings,
  Shield,
  UserCheck,
  Users,
} from 'lucide-react';

import type { NavConfig } from './nav.schema';

export const navConfig: NavConfig = {
  version: 1,
  items: [
    {
      id: 'dashboard',
      i18nKey: 'nav.dashboard',
      path: '/reports',
      icon: Gauge,
      order: 10,
      visibility: { roles: ['admin', 'manager', 'staff'] },
      meta: { surfaces: ['sidebar', 'top'] },
    },
    {
      id: 'elections',
      i18nKey: 'nav.elections',
      path: '/elections',
      icon: ClipboardList,
      order: 20,
      meta: { surfaces: ['sidebar', 'top'] },
      visibility: { hideWhen: ['unauthenticated'] },
      children: [
        {
          id: 'elections.detail',
          i18nKey: 'nav.elections.detail',
          path: '/elections/:id',
          breadcrumb: { i18nKey: 'nav.elections.detail' },
          exact: true,
          order: 1,
          meta: { surfaces: ['breadcrumb'] },
        },
      ],
    },
    {
      id: 'geoAreas',
      i18nKey: 'nav.geoAreas',
      path: '/geo-areas',
      icon: Globe2,
      order: 30,
      meta: { surfaces: ['sidebar', 'top'] },
      visibility: { hideWhen: ['unauthenticated'] },
      children: [
        {
          id: 'geoAreas.detail',
          i18nKey: 'nav.geoAreas.detail',
          path: '/geo-areas/:id',
          breadcrumb: { i18nKey: 'nav.geoAreas.detail' },
          exact: true,
          order: 1,
          meta: { surfaces: ['breadcrumb'] },
        },
      ],
    },
    {
      id: 'committees',
      i18nKey: 'nav.committees',
      path: '/committees',
      icon: Users,
      order: 40,
      meta: { surfaces: ['sidebar', 'top'] },
      visibility: { hideWhen: ['unauthenticated'] },
      children: [
        {
          id: 'committees.detail',
          i18nKey: 'nav.committees.detail',
          path: '/committees/:id',
          breadcrumb: { i18nKey: 'nav.committees.detail' },
          exact: true,
          order: 1,
          meta: { surfaces: ['breadcrumb'] },
        },
      ],
    },
    {
      id: 'voters',
      i18nKey: 'nav.voters',
      path: '/voters',
      icon: UserCheck,
      order: 50,
      meta: { surfaces: ['sidebar', 'top'] },
      visibility: { hideWhen: ['unauthenticated'] },
      children: [
        {
          id: 'voters.detail',
          i18nKey: 'nav.voters.detail',
          path: '/voters/:id',
          breadcrumb: { i18nKey: 'nav.voters.detail' },
          exact: true,
          order: 1,
          meta: { surfaces: ['breadcrumb'] },
        },
      ],
    },
    {
      id: 'candidates',
      i18nKey: 'nav.candidates',
      path: '/candidates',
      icon: Crown,
      order: 55,
      meta: { surfaces: ['sidebar', 'top'] },
      visibility: { hideWhen: ['unauthenticated'] },
      children: [
        {
          id: 'candidates.detail',
          i18nKey: 'nav.candidates.detail',
          path: '/candidates/:id',
          breadcrumb: { i18nKey: 'nav.candidates.detail' },
          exact: true,
          order: 1,
          meta: { surfaces: ['breadcrumb'] },
        },
      ],
    },
    {
      id: 'fieldOps',
      i18nKey: 'nav.fieldOps',
      icon: Shield,
      order: 60,
      meta: { surfaces: ['sidebar'] },
      visibility: { hideWhen: ['unauthenticated'] },
      children: [
        {
          id: 'fieldOps.agents',
          i18nKey: 'nav.fieldOps.agents',
          path: '/agents',
          icon: Shield,
          order: 10,
        },
        {
          id: 'fieldOps.volunteers',
          i18nKey: 'nav.fieldOps.volunteers',
          path: '/volunteers',
          icon: Users,
          order: 20,
          badge: { type: 'count', source: 'volunteers' },
        },
        {
          id: 'fieldOps.observations',
          i18nKey: 'nav.fieldOps.observations',
          path: '/observations',
          icon: BarChart3,
          order: 30,
          badge: { type: 'count', source: 'alerts' },
        },
        {
          id: 'fieldOps.zones',
          i18nKey: 'nav.fieldOps.zones',
          path: '/zones/mansoura',
          icon: MapPin,
          order: 40,
        },
      ],
    },
    {
      id: 'campaigns',
      i18nKey: 'nav.campaigns',
      path: '/campaigns',
      icon: Megaphone,
      order: 70,
      meta: { surfaces: ['sidebar', 'top'] },
      visibility: { hideWhen: ['unauthenticated'] },
      children: [
        {
          id: 'campaigns.automation',
          i18nKey: 'nav.campaigns.automation',
          path: '/automation',
          icon: BarChart3,
          order: 20,
        },
      ],
    },
    {
      id: 'reports',
      i18nKey: 'nav.reports',
      path: '/analytics',
      icon: BarChart3,
      order: 80,
      visibility: { flagsAny: ['betaReports'] },
      badge: { type: 'dot' },
      meta: { surfaces: ['sidebar', 'top'] },
    },
    {
      id: 'settings',
      i18nKey: 'nav.settings',
      path: '/settings',
      icon: Settings,
      order: 100,
      visibility: { roles: ['admin'] },
      meta: { surfaces: ['sidebar', 'top'] },
    },
  ],
};

export default navConfig;
